### ISSUE TITLE
Get-InvalidArgumentRecord params should match New-InvalidArgumentException

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/PSDscResources#10]
I've been copying a lot of the code from the CommonResourceHelper.psm1 and CommonTestsHelper.psm1 into some of the other DSC Resources (starting with FSRMDsc) and have noticed that the parameters and design of these functions is different. It would make them much easier to use (IMHO) if they matched.

For example I think this would be better:
```powershell
function Get-InvalidArgumentRecord
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [String]
        $Message,

        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [String]
        $ArgumentName
    )

    $argumentException = New-Object `
        -TypeName 'ArgumentException' `
        -ArgumentList @( $Message,$ArgumentName )
    $newObjectParams = @{
        TypeName = 'System.Management.Automation.ErrorRecord'
        ArgumentList = @( $argumentException, $ArgumentName, 'InvalidArgument', $null )
    }
    return New-Object @newObjectParams
}
```

This would mean that the call to throw the exception would be identical (except for the cmdlet name) to the call to create the ErrorRecord to use in a unit test.

This is definitely a minor thing, but as I'm adopting this across more and more resources it would make it way easier :smile:

**Comment by PlagueHO** [comment]
It would also be awesome if this also applied to Get-InvalidOperationRecord as well. And I think these should both be in CommonTestHelpers.psm1 rather than in the helper module for the specific tests.

The reason I suggest this is that I'm trying to ensure all resources I work on match what you're doing with PSDscResources. So I'm copying and including these modules in the repos.

Hope that makes sense!

**Comment by kwirkykat** [comment]
@PlagueHO While I was working on ServiceSet, I found that this function wasn't actually necessary since you can just check for the correct error message in Pester without the entire error record as you can see [here](https://github.com/PowerShell/PSDscResources/blob/dev/Tests/Unit/MSFT_GroupResource.Tests.ps1#L572).

So I've actually taken this function out in my most recent code. Do you think it's worth it to keep it?

**Comment by PlagueHO** [comment]
@kwirkykat - oh wow! Cool! I didn't know this.

I only ever test the error message on the exception object anyway, so IMHO we should get rid of it - simpler is better I think.

I think so far I've only used this function in FSRMDsc and FileContentDsc (work in progress). So removing it for me wouldn't be too difficult. If you decide to remove it, let me know and I'll do the same in the above resources because I'd prefer to keep in line with PSDscResources.

**Comment by kwirkykat** [comment]
Closing this issue since this function was removed
