### ISSUE TITLE
Registry: ValueName should be optional

### ISSUE THREAD

**Issue by VertigoRay** [PowerShell/PSDscResources#101]
I feel like the implementation of `ValueName` as an empty string (without `ValueType`
or `ValueData`) to target a Key is a bit clunky. An empty string intuitively targets the `(Default)` value. Although removal of the `(Default)` value does imply removal of the Key, it's not intuitive by design. With all due respect, it feels a bit like a hack to add the ability of Key removal.

I believe that `ValueName` should not be a required property. It's more intuitive that Key removal look like this:

```powershell
Registry Test
{
    Ensure = 'Absent'
    Key = 'HKLM:\Software\Test'
}
```

Making this improvement would not require current functionality to break though. As I stated already, removal of the `(Default)` value implies removal of the Key. We would just be adding a more intuitive Key removal option. This would also allow for additional properties/features to be implemented that don't require a `ValueName` name property.

**Comment by johlju** [comment]
I understand what you getting at. But `ValueName` is of the type qualifier `Key`, it is required to be set to be able to specify more than one name under the same key. That is why it needs/can be set to a blank value for the addition and removal of a key. 

```powershell
Registry Registry1
{
    Ensure = 'Present'
    Key = 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment'
    ValueName = ''
}

Registry Registry2
{
    Ensure = 'Present'
    Key = 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment'
    ValueName = 'MyValue1'
    ValueType = 'Binary'
    ValueData = '0x00'
    Force = $true
}

Registry Registry3
{
    Ensure = 'Present'
    Key = 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment'
    ValueName = 'MyValue2'
    ValueType = 'Binary'
    ValueData = '0x00'
    Force = $true
}

Registry Test
{
    Ensure = 'Absent'
    Key = 'HKLM:\Software\Test'
    ValueName = ''
}

```

I think your proposal might work if there was two resources. Not certain splitting up the resource into two is worth the effort? 

Resource `RegistryKey` would have property `Key` as the type qualifier `Key`, and resource 'RegistryValue' would have both `Key` and `ValueName` as the type qualifier `Key`
```
RegistryKey Key1
{
    Ensure = 'Present'
    Key = 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment'
}

RegistryValue Value1
{
    Ensure = 'Present'
    Key = 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment'
    ValueName = 'MyValue1'
    ValueType = 'Binary'
    ValueData = '0x00'
    Force = $true
}
```

**Comment by VertigoRay** [comment]
I'd have to do some more testing, but can you not default the ValueName to an empty string and still use it as the Key without providing it as a property in the resource configuration?

**Comment by johlju** [comment]
If a property is Key in the schema.mof it need to be provided in the configuration. Also mandatory parameters should not have default values since they does not bring any value since the parameter must be set when calling the function.
