### ISSUE TITLE
Replacement for xRemoteFile resource

### ISSUE THREAD

**Issue by adhodgson1** [PowerShell/PSDscResources#102]
Hi,

Updating a bunch of DSC configurations to remove experimental modules etc.  What is the replacement (if any) for xRemoteFile from xPSDesiredStateConfiguration?

I thought I could use the File resource with the source being a URL but reading comments this doesn't seem to be the case.

**Comment by johlju** [comment]
There are no equivalent to xRemoteFile in this repository. 

Please also note that 'x' no longer have to mean experimental. There are a lot of resource that still is prefixed by 'x' but haven't yet been renamed to the new naming convention, see [DSC Resource Naming Guidelines]((https://blogs.msdn.microsoft.com/powershell/2017/12/08/dsc-resource-naming-and-support-guidelines/).

**Comment by johlju** [comment]
There are no replacement for xRemoteFile, please use the one in xPSDesiredStateConfiguration. If there are any problems with that resource, please submit an issue in the xPSDesiredStateConfiguration repository.

Resources moved here from xPSDesiredStateConfiguration will most likely have the same functionality, only difference would be that the code would be cleanup against the style guideline, and resources in this resource module will not be supported on PowerShell version 5.0 and lower.
There are currently no plans to move xRemoteFile.
