### ISSUE TITLE
Avoid using the Win32_Product WMI class

### ISSUE THREAD

**Issue by johlju** [PowerShell/PSDscResources#103]
This repository has reference to Win32_Product WMI class. As reported in issue https://github.com/PowerShell/DscResources/issues/108, if possible then avoid using the Win32_Product.

>If you are using a group policy with the WMIFilter that queries Win32_Product, modify the filter to use Win32reg_AddRemovePrograms
>...
>Win32reg_AddRemovePrograms is a much lighter and effective way to do this, which avoids the calls to do a resiliency check, especially in a locked down environment. So when using Win32reg_AddRemovePrograms we will not be calling on msiprov.dll and will not be initiating a resiliency check.
>https://support.microsoft.com/en-us/kb/974524

There might not be possible to avoid using it, but for someone to determine that an issue is opened in very repository that has a reference to Win32_Product WMI class.

**Comment by danielboth** [comment]
Win32_Product is only used in two examples in this repository:

https://github.com/PowerShell/PSDscResources/blob/900cfcd844200205370d54390a6dadcc4df3c357/Examples/Sample_MsiPackage_InstallPackageFromFile.ps1#L13
https://github.com/PowerShell/PSDscResources/blob/900cfcd844200205370d54390a6dadcc4df3c357/Examples/Sample_MsiPackage_UninstallPackageFromFile.ps1#L13

I guess that's ok, or should we add a disclaimer on top?

**Comment by johlju** [comment]
Yes, I agree with that this is okay having that in the examples. I don’t see the need for a disclaimer. Closing this. If someone disagree we can reopen it.
