### ISSUE TITLE
Help needed - Facing an issue when trying to install prerequisites

### ISSUE THREAD

**Issue by GabCeb95** [PowerShell/PSDscResources#114]
Hi !! Thanks in advance for any help!

I have been struggling with this error, it is giving me an error with the AddServiceToLocalAdmins piece, as you can see the error says “The user name or password is incorrect” but I already double checked and the credentials are correct, so I am trying to find a way about how to fix this issue…

![error](https://user-images.githubusercontent.com/18234563/45003481-4f9b3500-afa0-11e8-9c38-931a8a6a7e65.PNG)

This issue is happening when running the prerequisites DSC configuration command: Invoke-SPPLAPreRequisiteDscConfiguration -ConfigDataFilePath ./SPPLAConfigData.psd1 –Verbose

Do you have any idea what can be happening here? I will really appreciate it if you can give me any idea about how can I solve this issue

Note: I went to each of the servers and the account was added correctly, but the scripts does not complete successfully because of this error...

**Comment by johlju** [comment]
Did you see this commen https://github.com/PowerShell/PSDscResources/issues/82#issuecomment-325716274, did it help?

Also, as per this https://github.com/PowerShell/SharePointDsc/issues/861#issuecomment-417612068, did you talk to the consultants delivering this service?

**Comment by johlju** [comment]
Can you extract the part of the configuration that uses the `Group` resource, and run it individually with the verbose output. 
Then please provide the configuration and verbose output here (with obfuscated information). Also please provide the current members of the local admin group (obfuscated as well).
