### ISSUE TITLE
Script with PsDscRunAsCredential not working

### ISSUE THREAD

**Issue by paololec** [PowerShell/PSDscResources#115]
Script with PsDscRunAsCredential not working. Go to error.
Using Credential work fine.

I try the code:
```
 $SQLpath = "C:\Install\SQLBinaries"
  Script ExtractSQLISO         {
            SetScript = 
            {
                New-Item -Path "$using:SQLpath" -ItemType Directory
                $mountResult = Mount-DiskImage -ImagePath 'C:\Install\en_sql_server_2017_developer_x64_dvd_11296168.iso' -PassThru
                $volumeInfo = $mountResult | Get-Volume
                $driveInfo = Get-PSDrive -Name $volumeInfo.DriveLetter
                Copy-Item -Path ( Join-Path -Path $driveInfo.Root -ChildPath '*' ) -Destination "$using:SQLpath" -Recurse
                Dismount-DiskImage -ImagePath 'C:\Install\en_sql_server_2017_developer_x64_dvd_11296168.iso'
            }
            TestScript = { Test-Path "$using:SQLpath\setup.exe" }
            GetScript = { @{ Result = (Get-ItemPropertyValue "$using:SQLpath\setup.exe" -Name "Name" ) } }
            PsDscRunAsCredential= $Cred_admin  
       }
```

                                                                                               
PSVersion                      5.1.14393.2430                                                                                                
PSEdition                      Desktop                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                       
BuildVersion                   10.0.14393.2430                                                                                               
CLRVersion                     4.0.30319.42000                                                                                               
WSManStackVersion              3.0                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                           
SerializationVersion           1.1.0.1

**Comment by johlju** [comment]
What error are you getting? Can you please provide the verbose logs (containing the error) when you run that? Obfuscate any sensitive information from the logs.

**Comment by johlju** [comment]
Also, in the snippet above, it does not show what resource you are using. Do you have `Import-DscResource -ModuleName 'PSDscResources'` so you are not using the built-in resource?

**Comment by paololec** [comment]
Yes using: Import-DscResource -ModuleName PSDscResources 
Using the built-in work fine, but I need PsDscResources for other dsc resource.

The error is:
PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: 
System.InvalidOperationException: The set script threw an error. ---> System.Management.Automation.DriveNotFoundException: Cannot find 
drive. A drive with the name 'E' does not exist.
   at System.Management.Automation.SessionStateInternal.GetDrive(String name, Boolean automount)
   at System.Management.Automation.SessionStateInternal.GetDrive(String name, Boolean automount)
   at Microsoft.PowerShell.Commands.DriveMatchingCoreCommandBase.GetMatchingDrives(String driveName, String[] providerNames, String scope)
   at Microsoft.PowerShell.Commands.GetPSDriveCommand.ProcessRecord()
   --- End of inner exception stack trace --- 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

**Comment by johlju** [comment]
It seems `Get-PSDrive` does not see the new "disk" in the session. Getting all the disk from the filesystem solves this.

Changing
```powershell
$driveInfo = Get-PSDrive -Name $volumeInfo.DriveLetter
```

To
```powershell
$driveInfo = Get-PSDrive -PSProvider FileSystem -Name $volumeInfo.DriveLetter
```

**Comment by johlju** [comment]
My previous comment is not correct. But the problem is `Get-PSDrive`, not the authentication.
If the line 34 is comment out, the configuration fails with the error you mentioned above. If line 34 is not commented out, the script works. So must be that the session has not been updated with the drives, and enumeration the drives updates the session. This is my guess at least.

Full script that works.

```powershell
$cd = @{
    AllNodes = @(
        @{
            NodeName = 'localhost'
            PSDscAllowPlainTextPassword = $true
            PSDscAllowDomainUser = $true
        }
    )
}

$SQLpath = "C:\Install\SQLBinaries"

Configuration TestSpeculationControl
{
    param(
    [PSCredential]
    $Cred_admin
    )

    Import-DscResource -ModuleName PSDScResources 

    Node localhost
    {
        Script ExtractSQLISO         
        {
            SetScript = 
            {
                Write-Verbose "User: $($PsDscContext.RunAsUser)" -Verbose
                New-Item -Path "$using:SQLpath" -ItemType Directory -Force
                $mountResult = Mount-DiskImage -ImagePath 'c:\temp\en_sql_server_2017_enterprise_x64_dvd_11293666.iso' -PassThru
                Write-Verbose "ImagePath: $($mountResult.ImagePath)" -Verbose
                $volumeInfo = $mountResult | Get-Volume
                Write-Verbose "DriveLetter: $($volumeInfo.DriveLetter)" -Verbose
                Get-PSDrive | ForEach-Object { Write-Verbose "Drive: $($_.Name)" -Verbose }
                $driveInfo = Get-PSDrive -Name $volumeInfo.DriveLetter

                Write-Verbose "DriveInfo: $($driveInfo.Root)" -Verbose
                Copy-Item -Path ( Join-Path -Path $driveInfo.Root -ChildPath '*' ) -Destination "$using:SQLpath" -Recurse
                Dismount-DiskImage -ImagePath 'C:\temp\en_sql_server_2017_enterprise_x64_dvd_11293666.iso'
            }

            TestScript = { 
                Test-Path "$using:SQLpath\setup.exe" 
            }

            GetScript = {
                @{
                    Result = (Get-ItemPropertyValue "$using:SQLpath\setup.exe" -Name "Name" )
                    }
            }

            PsDscRunAsCredential= $Cred_admin  
       }
    }
}

TestSpeculationControl -OutputPath C:\temp -ConfigurationData $cd -Cred_admin (get-credential)

Start-DscConfiguration -Path c:\temp -Wait -Force -Verbose 
```

**Comment by paololec** [comment]
I confirm, the enumeration "refresh" solve the problem. 
Add before $driveInfo :
Get-PSDrive | ForEach-Object { Write-Verbose "Drive: $($_.Name)" -Verbose }

Thanks so much.
