### ISSUE TITLE
Why is PSDscResources not appearing when doing a Get-Module -ListAvailable? 

### ISSUE THREAD

**Issue by kinwolfqc** [PowerShell/PSDscResources#149]
As the title says, anyone knows why the module isn't appearing with a Get-module on the target host?  The problem this cause is when trying to install PSDscResources with scripts or system like ansible that rely on the command  `Get-Module -ListAvailable | Where-Object { ($_.name -eq $Name)  `  to list what version of a module is present and to install it of not present.  Because PSDscResources is not appearing, it is always installed.  

Any insight on how to detect it is installed, and which version?

**Comment by PlagueHO** [comment]
Hi @kinwolfqc - I tried to replicate this on a Windows 10 machine with 2.10.0.0 installed using PowerShellGet (e.g. `Install-Module -Name PSDscResource`) and the `Get-Module -Name PSDscResource` -ListAvailable found the resource OK and returned the 2.10.0.0 version.

Note: You shouldn't need the `Where-Object` - just use the `-Name` parameter on the Get-Module.

How did you install the PSDscResource module and is it in a path in the `$ENV:PSModulePath` ?

**Comment by kinwolfqc** [comment]
I found the problem, it is related to the nuspec file, and not the resource itself.   In the nuspec file, the version is 2.10.0 (not 2.10.0.0) and for some reason, when downloading the nupkg from PowershellGallery, but using it on our internal nuget server, it will install PSDscResource under \powershell\modules\PSDscResource\2.10.0 (notice the missing .0 at the end)

Because the version in the manifest is 2.10.0.0, powershell refuse to load it(found that out by using Test-ModuleManifest on it and it complained that the folder version wasn't correct)

Strangely, installing directly from powershellgallery installs it correctly under PSDscResource\2.10.0.0  So the bug seems related to nuget.server instead.  
To fix this for the moment, I modified manually the nupsec file to mention 2.10.0.0.  I had the same problem with StorageDSC.  The nuspec file creation is highly inconsistent since it seems many DSC resources use correctly 4 dots for the version in it, while others use only 3(and those then refuse to load when installed form the local nuget)

Closing this since it's not related to the resource itself after all.  Thanks!

**Comment by PlagueHO** [comment]
Actually, now that you mention it @kinwolfqc - we've found the exact same problem happening on our Nexus servers when used with Nuget - Nuget exhibits that behavior for some reason (stripping off the revision number if it is 0). We were using Nuget because of some issues with PowerShellGet (https://github.com/PowerShell/PowerShellGet) module. But I think most of these are "mostly" resolved now.
