### ISSUE TITLE
WindowsCapability resource

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/PSDscResources#168]
It looks like we need a new resource to support the "WindowsCapability" cmdlets.  I can create the PR and get it rolling, I just wanted to get feedback first.  We could try to merge this in to Feature or OptionalFeature, but I think this deserves its own resource?  As an alternative, we could consider putting it in ComputerManagementDsc?

Is someone else already working on this?

https://docs.microsoft.com/en-us/powershell/module/dism/add-windowscapability
https://docs.microsoft.com/en-us/powershell/module/dism/get-windowscapability
https://docs.microsoft.com/en-us/powershell/module/dism/remove-windowscapability

cc
@kwirkykat @PlagueHO @gaelcolas @johlju @mhendric

**Comment by mhendric** [comment]
Are we still adding features to PSDscResources? I'm still confused on this. I thought we were not supposed to add anything new other than bug / style fix type updates, and anything new and major had to go in xPSDesiredStateConfiguration (or another appropriate module).

**Comment by gaelcolas** [comment]
Nope. We said no new resources here so ComputerManagementDsc might be a better candidate. Flight's about to take off so I'll catch up on the other side...

**Comment by PlagueHO** [comment]
I'm in favor of ComputerManagementDsc myself as it does seem like the logical place for it and helps us avoid lots of single resource modules.

**Comment by johlju** [comment]
I agree with adding this to ComputerManagementDsc too. 

@gaelcolas maybe you can use the GitHub move issue feature to move this issue over to ComputerManagementDsc?

**Comment by PlagueHO** [comment]
This has been added over in ComputerManagementDsc.
