### ISSUE TITLE
Package missing build number in version Metadata

### ISSUE THREAD

**Issue by General-Fault** [PowerShell/PSDscResources#187]
This package is published in PowerShell Gallery with version 2.12.0, however the module version is 2.12.0.0. Consequentially, the module is is installed to "C:\Program Files\WindowsPowerShell\Modules\PSDscResources\2.12.0\". This does not precisely match the release version number (note the missing ".0"). Unfortunately this causes a problem when this module is referenced by specific version.

**Comment by PlagueHO** [comment]
Hi @General-Fault - this is a behavior of the underlying packaging technology (Nuget). It is discussed in depth over in this issue: https://github.com/PowerShell/DscResources/issues/508

**Comment by General-Fault** [comment]
@PlagueHO  Thank you. I just figured this out myself when the problem disappeared after updating the PowerShellGet package provider.
