### ISSUE TITLE
Group resource Exception when Groupname is 'Users'

### ISSUE THREAD

**Issue by stinos** [PowerShell/PSDscResources#26]
Not sure what the problem is. Only occurrs for the Users group.

```
Configuration DscAddGroup {
  Import-DscResource -ModuleName 'PSDscResources'

  Node 'localhost' {
    Group Users {
      GroupName = 'Users'
    }
  }
}

DscAddGroup
Test-DscConfiguration -Path .\DscAddGroup
```

yields

```
PowerShell DSC resource MSFT_GroupResource  failed to execute Test-TargetResource functionality with error message: Exception calling
".ctor" with "2" argument(s): "Server names cannot contain a space character."
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
```

If the name of the group is changed to any other existing or non-existing group all works ok.
Tested on a fresh Windows 10 installation.
Using 'PSDesiredStateConfiguration' instead the error is the same though somewhat more verbose:

```
Exception calling ".ctor" with "2" argument(s): "Server names cannot contain a space character."
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
    + PSComputerName        : localhost

The PowerShell DSC resource '[Group]Users' with SourceInfo 'C:\Users\admin\Desktop\TestConfig.ps1::5::5::Group' threw one or more
non-terminating errors while running the Test-TargetResource functionality. These errors are logged to the ETW channel called
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
```

**Comment by kwirkykat** [comment]
@stinos Group is currently designed to take only users as members and not groups. It seems to work with domain groups because they are treated more like users, but local groups won't work.

**Comment by kwirkykat** [comment]
@stinos Sorry. I was thinking of a different issue before.
Yes, this is a bug. I will look into it.

This error seems to be coming up when the resource has issues resolving members of the group.
Though you aren't defining any members (which is where this error normally pops up), it may be that the resource is trying to resolve the existing members of the group without the proper credentials or access to domains. Which it probably shouldn't do since you didn't define any members...

Have you tried this configuration while providing a credential that has enough permissions to resolve all the members in the group?

**Comment by kwirkykat** [comment]
@stinos I can confirm that the resource is erroneously attempting to retrieve the existing group member even though members were not specified. Fixing this now.

**Comment by stinos** [comment]
> Though you aren't defining any members (which is where this error normally pops up)

I'm pretty sure I first tried with members as well, and that gave the samer error.

> Have you tried this configuration while providing a credential that has enough permissions to resolve all the members in the group?

No and I don't have access to the testing pc until monday.
But this was all tested locally against localhost, are you saying the system account running DSC doesn't have those permissions?

**Comment by kwirkykat** [comment]
@stinos DSC should have the correct permissions. I think in this case maybe you have a user from the 'NT SERVICE' or 'NT AUTHORITY' domains in the Users group which we are having problems with in Group at the moment as the external call to Get-PrincipalContext doesn't seem to like those domains.

I'm working on it.

**Comment by kwirkykat** [comment]
Similar issues over in xPSDSC: https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/288, https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/250

**Comment by stinos** [comment]
Thanks for the fix, I'll verify this a.s.a.p.

**Comment by stinos** [comment]
Works for me now, thanks!
