### ISSUE TITLE
Importing PSDscResources to Azure Automation DSC fails

### ISSUE THREAD

**Issue by janegilring** [PowerShell/PSDscResources#46]
When trying to import the PSDscResources module to Azure Automation, it fails with the following error:
> Error extracting the activities from module PSDscResources. Extraction failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: An error occurred during module validation. When importing the module to an internal PowerShell session, it was not able to be loaded by PowerShell. There is likely an issue with the contents of the module that results in PowerShell's not being able to load it. Please verify that the module imports successfully in a local PowerShell session, correct any issues, and then try importing again.

**Comment by kwirkykat** [comment]
@janegilring What is the full PowerShell/WMF version of the machine you are trying to import PSDscResources on?

**Comment by janegilring** [comment]
The import operation is running in Azure Automation, so it`s the version they are using for their sandbox/runbook workers. I think that is WMF 5.1.

**Comment by bgelens** [comment]
@janegilring Azure Automation is running 5.0 still. Which means this module is not supported

**Comment by janegilring** [comment]
Thanks, that explains it.

**Comment by ruandersMSFT** [comment]
Adding a comment for any forward visibility, as this noted limitation has been updated now.  PSDscResources is now usable.  WMF 5.1 availability can be reviewed in [Azure Desired State Configuration extension version history](https://docs.microsoft.com/en-us/azure/automation/automation-dsc-extension-history).
