### ISSUE TITLE
invoke-dscresource says that a resource is not found

### ISSUE THREAD

**Issue by kev111** [PowerShell/PSDscResources#48]
PS C:\Windows\system32> Invoke-DscResource -Method test -Name WindowsFeature -Property @{name='RSAT-AD-PowerShell';IncludeAllSubFeature=$true;ens
Present'} -module PSDscResources -Verbose
Invoke-DscResource : Resource WindowsFeature was not found.
At line:1 char:1
+ Invoke-DscResource -Method test -Name WindowsFeature -Property @{name ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-DscResource], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.DesiredStateConfiguration.Commands.InvokeDscResourceMethodCommand

**Comment by mbreakey3** [comment]
Are you sure PSDscResources is installed as well as the latest version of PowerShell on this machine? Can you run Get-DscResource and post the results of that here?

**Comment by kev111** [comment]
PS C:\Windows\system32> $psversiontable.psversion
 
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14409  1005
 
 
PS C:\Windows\system32> get-module psdscresources
 
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   2.5.0.0    psdscresources
 
 
PS C:\Windows\system32> get-dscresource windowsfeature
ImportCimAndScriptKeywordsFromModule : Cim deserializer threw an error when deserializing file C:\Program
Files\WindowsPowerShell\Modules\Intigua\1.0.0.9\DSCResources\Intigua_Connector\Intigua_Connector.Schema.mof.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:4143 char:29
+ ...     $null = ImportCimAndScriptKeywordsFromModule -Module $mod -Resour ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], PSInvalidOperationException
    + FullyQualifiedErrorId : System.Management.Automation.PSInvalidOperationException,ImportCimAndScriptKeywordsFromModule
 
ImportCimAndScriptKeywordsFromModule : Syntax error:
At line:5, char:51
Buffer:
re Server URL."), String^ CoreSe
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:4143 char:29
+ ...     $null = ImportCimAndScriptKeywordsFromModule -Module $mod -Resour ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], CimException
    + FullyQualifiedErrorId : Microsoft.Management.Infrastructure.CimException,ImportCimAndScriptKeywordsFromModule
 
ImportCimAndScriptKeywordsFromModule : Cim deserializer threw an error when deserializing file C:\Program
Files\WindowsPowerShell\Modules\Intigua\1.0.0.8\DSCResources\Intigua_Connector\Intigua_Connector.Schema.mof.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:4143 char:29
+ ...     $null = ImportCimAndScriptKeywordsFromModule -Module $mod -Resour ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], PSInvalidOperationException
    + FullyQualifiedErrorId : System.Management.Automation.PSInvalidOperationException,ImportCimAndScriptKeywordsFromModule
 
ImportCimAndScriptKeywordsFromModule : Syntax error:
At line:5, char:51
Buffer:
re Server URL."), String^ CoreSe
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:4143 char:29
+ ...     $null = ImportCimAndScriptKeywordsFromModule -Module $mod -Resour ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], CimException
    + FullyQualifiedErrorId : Microsoft.Management.Infrastructure.CimException,ImportCimAndScriptKeywordsFromModule
 
 
ImplementedAs   Name                      ModuleName                     Version    Properties
-------------   ----                      ----------                     -------    ----------
PowerShell      WindowsFeature            PSDesiredStateConfiguration    1.1        {Name, Credential, DependsOn, Ensure...}
PowerShell      WindowsFeature            PSDscResources                 2.2.0.0    {Name, Credential, DependsOn, Ensure...}
PowerShell      WindowsFeature            PSDscResources                 2.1.0.0    {Name, Credential, DependsOn, Ensure...}
PowerShell      WindowsFeature            PSDscResources                 2.3.0.0    {Name, Credential, DependsOn, Ensure...}
PowerShell      WindowsFeature            PSDscResources                 2.5.0.0    {Name, Credential, DependsOn, Ensure...}
PowerShell      WindowsFeature            PSDscResources                 2.4.0.0    {Name, Credential, DependsOn, Ensure...}

**Comment by kev111** [comment]
```text
PS C:\Windows\system32> $psversiontable.psversion
 
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14409  1005
 
 
PS C:\Windows\system32> get-module psdscresources
 
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   2.5.0.0    psdscresources
 
 
PS C:\Windows\system32> get-dscresource windowsfeature
ImportCimAndScriptKeywordsFromModule : Cim deserializer threw an error when deserializing file C:\Program
Files\WindowsPowerShell\Modules\Intigua\1.0.0.9\DSCResources\Intigua_Connector\Intigua_Connector.Schema.mof.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:4143 char:29
+ ...     $null = ImportCimAndScriptKeywordsFromModule -Module $mod -Resour ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], PSInvalidOperationException
    + FullyQualifiedErrorId : System.Management.Automation.PSInvalidOperationException,ImportCimAndScriptKeywordsFromModule
 
ImportCimAndScriptKeywordsFromModule : Syntax error:
At line:5, char:51
Buffer:
re Server URL."), String^ CoreSe
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:4143 char:29
+ ...     $null = ImportCimAndScriptKeywordsFromModule -Module $mod -Resour ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], CimException
    + FullyQualifiedErrorId : Microsoft.Management.Infrastructure.CimException,ImportCimAndScriptKeywordsFromModule
 
ImportCimAndScriptKeywordsFromModule : Cim deserializer threw an error when deserializing file C:\Program
Files\WindowsPowerShell\Modules\Intigua\1.0.0.8\DSCResources\Intigua_Connector\Intigua_Connector.Schema.mof.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:4143 char:29
+ ...     $null = ImportCimAndScriptKeywordsFromModule -Module $mod -Resour ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], PSInvalidOperationException
    + FullyQualifiedErrorId : System.Management.Automation.PSInvalidOperationException,ImportCimAndScriptKeywordsFromModule
 
ImportCimAndScriptKeywordsFromModule : Syntax error:
At line:5, char:51
Buffer:
re Server URL."), String^ CoreSe
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:4143 char:29
+ ...     $null = ImportCimAndScriptKeywordsFromModule -Module $mod -Resour ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], CimException
    + FullyQualifiedErrorId : Microsoft.Management.Infrastructure.CimException,ImportCimAndScriptKeywordsFromModule
 
 
ImplementedAs   Name                      ModuleName                     Version    Properties
-------------   ----                      ----------                     -------    ----------
PowerShell      WindowsFeature            PSDesiredStateConfiguration    1.1        {Name, Credential, DependsOn, Ensure...}
PowerShell      WindowsFeature            PSDscResources                 2.2.0.0    {Name, Credential, DependsOn, Ensure...}
PowerShell      WindowsFeature            PSDscResources                 2.1.0.0    {Name, Credential, DependsOn, Ensure...}
PowerShell      WindowsFeature            PSDscResources                 2.3.0.0    {Name, Credential, DependsOn, Ensure...}
PowerShell      WindowsFeature            PSDscResources                 2.5.0.0    {Name, Credential, DependsOn, Ensure...}
PowerShell      WindowsFeature            PSDscResources                 2.4.0.0    {Name, Credential, DependsOn, Ensure...}
```

**Comment by mbreakey3** [comment]
It looks like you've got quite a few versions of PSDscResources installed, that could be the problem. when you install/import a module you can specify which version you want to use, but with Invoke-DscResource, I'm not sure if there's an easy way to do that. You could just import the module and specify the version you want and then call Test-TargetResource or you could delete any unused versions of PSDscResources if you don't need multiple.

**Comment by mbreakey3** [comment]
To use Invoke-DscResource when multiple versions are installed, you're going to have to specify the fully qualified name of the module:

Invoke-DscResource -Method Test -Name WindowsFeature -Property @{Name='RSAT-AD-PowerShell'; IncludeAllSubFeature=$true; ens Present'} -ModuleName @{ModuleName=’PSDscResources’; ModuleVersion=2.2.0.0’} -Verbose

**Comment by mbreakey3** [comment]
Let me know if this is still causing issues
