### ISSUE TITLE
PSDscResources fails to be imported into Azure Automation

### ISSUE THREAD

**Issue by 4c74356b41** [PowerShell/PSDscResources#56]
Uploading from the gallery or directly from powershellgallery.com (giving azure automation a link) doesn't make a difference

![2017-04-23_11-58-32](https://cloud.githubusercontent.com/assets/16194643/25312220/5fd16d52-281c-11e7-82c7-b650ee0bb0e9.png)

**Comment by bgelens** [comment]
@4c74356b41 Azure Automation is still at PSv5.0. The module requires 5.1 unfortunately. Probably best to address at UserVoice for Azure Automation

**Comment by 4c74356b41** [comment]
Hey there, do you know any eta around this?

**Comment by 4c74356b41** [comment]
this works now, probably fixed
