### ISSUE TITLE
Update Environment resource so that whenever $path is set to $true, the name will be ignored 

### ISSUE THREAD

**Issue by mbreakey3** [PowerShell/PSDscResources#60]
Currently the Environment resource limits the use of setting the PATH variable, specifically with partial configurations. 

See issue #59 

Link to discussion on issue [here](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11088876-dsc-environment-resource-does-not-allow-duplicate)

**Comment by kwirkykat** [comment]
@mbreakey3 Is this a bug or an enhancement?

**Comment by kwirkykat** [comment]
This is a duplicate of #59. To consolidate the discussion, I'm closing this issue and any further discussion on this can happen in that issue.
