### ISSUE TITLE
Service resource using Name as Key disallows the ability to stop / start a service

### ISSUE THREAD

**Issue by TheBlackMini** [PowerShell/PSDscResources#62]
Recommend using something else for a key in this resource.
Maybe a GUID?

**Comment by kwirkykat** [comment]
@TheBlackMini Can you elaborate?

**Comment by TheBlackMini** [comment]
```
Configuration RestartMe {
    Node localhost
    {
        Service StopDNS
        {
	        Name = "Dnscache"
	        State = "Stopped"
        }

        # Do something else here

        Service StartDNS
        {
	        Name = "Dnscache"
	        State = "Running"
        }
    }
}

RestartMe
```

Running the above code will produce the following error:

> Test-ConflictingResources : A conflict was detected between resources '[Service]StopDNS (::4::9::Service)' and '[Service]StartDNS (::12::9::Service)' in node 
> 'localhost'. Resources have identical key properties but there are differences in the following non-key properties: 'State'. Values 'Stopped' don't match values 
> 'Running'. Please update these property values so that they are identical in both cases.

**Comment by johlju** [comment]
@TheBlackMini That is how DSC is design. A configuration is a desired state, either the state of the service should _always_ be started or the service should _never_ be started. What you are trying to accomplish is a program flow, which is not the intended usage scenario for DSC.

To solve your particular use case you need a resource that can detect that the state of what you trying to do is not in the correct state. If the Test-method of the resource finds that the state is not in desired state then this new resource calls the Set-method which stops the correct service, does the needed change, and then start the previous stopped service (optionally with any dependent services that was also stopped). 
If what you trying to do is not present in any of the current resources, then you might be able to use the Script-resource to do this correctly.
I hope I explained it good enough. :)

But also, if this is a task that you are trying to accomplish is a common task (more users would benefit by it), then please submit an issue in the correct DSC module repository for this to be implemented.

**Comment by bgelens** [comment]
Also, please vote [here](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11088639-enable-service-restart-and-similar-scenarios-in-ds) to get platform support of what you are trying to do.
