### ISSUE TITLE
if (-not (Test-IsNanoServer)) fails on 2008r2 systems

### ISSUE THREAD

**Issue by blackdynamite595** [PowerShell/PSDscResources#65]
if (-not (Test-IsNanoServer)) calls Get-ComputerInfo

Get-ComputerInfo : Unable to find an entry point named 'GetFirmwareType' in DLL 'kernel32.dll'.

This only fails on 2008r2. Known issue: https://github.com/PowerShell/PowerShell/issues/3023 Works on 2012 and above.

Need to add some sort of test for OS version first:

$osbuild = (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name CurrentBuild).CurrentBuild

if $osbuild -lt "9200"

**Comment by aydeisen** [comment]
I ran into this issue yesterday while using version 2.8.0.0 of the PsDscResources Module.  


Based on @iSazonov response from 20 JAN 2017 on the issue (PowerShell/PowerShell#3023), I modified my local copy of the `Test-IsNanoServer` function in the `CommonResourceHelper.psm1` file with the below.  I don't know whether it complies with HQRM, but it tested successfully, and continues to work properly.
```powershell

function Test-IsNanoServer
{
    [OutputType([Boolean])]
    [CmdletBinding()]
    param ()

    $osVersion = [System.Environment]::OSVersion.Version
    $isNanoServer = $false
    switch ($osVersion)
    {
        {$_.Major -lt 6}
        {
            $computerInfo = $null; break
        }
        {($_.Major -eq 6) -and ($_.Minor -lt 2)}
        {
            $computerInfo = $null; break
        }
        default
        {
            if (Test-CommandExists -Name 'Get-ComputerInfo')
            {
                $computerInfo = Get-ComputerInfo -ErrorAction 'SilentlyContinue'

                if ($null -ne $computerInfo)
                {
                    $computerIsServer = 'Server' -ieq $computerInfo.OsProductType

                    if ($computerIsServer)
                    {
                        $isNanoServer = 'NanoServer' -ieq $computerInfo.OsServerLevel
                    }
                }
            }
        }
    }
    return $isNanoServer
}

```
