### ISSUE TITLE
Cannot manage registry key with forward slash

### ISSUE THREAD

**Issue by jozefizso** [PowerShell/PSDscResources#68]
I'm working on PowerShell DSC module to manage FogBugz application. Their registry keys contains forward slashes. This cannot be managed by DSC right now.

Sample registry key used by FogBugz web app
![screenshot_060817_100444_pm](https://user-images.githubusercontent.com/287778/26948659-77eec4e4-4c97-11e7-8000-d2110a8d3aae.jpg)

Sample configuration:

```
  Registry FogBugzRegistry_fDebug
  {
      Key         = "HKEY_LOCAL_MACHINE\SOFTWARE\Fog Creek Software\FogBugz\C:/Program Files (x86)/FogBugz/website"
      ValueName   = "fDebug"
      ValueData   = "0"
      Ensure      = "Present"
  }
```

The error message when applying DSC:
```
PowerShell DSC resource MSFT_RegistryResource  failed to execute Test-TargetResource functionality with error message: (ERROR) Invalid PSDrive 'HKEY_LOCAL_MACHINE\SOFTWARE\Fog
Creek Software\FogBugz\C' specified in registry key 'HKEY_LOCAL_MACHINE\SOFTWARE\Fog Creek Software\FogBugz\C:/Program Files (x86)/FogBugz/website'
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
```

Expected behavior: I should be able to manage any valid registry key value by DSC.

Reference: https://msdn.microsoft.com/en-us/library/ms724946(VS.85).aspx
> Each key has a name consisting of one or more printable characters. Key names are not case sensitive. Key names cannot include the backslash character (\), but any other printable character can be used. Value names and data can include the backslash character.

**Comment by kwirkykat** [comment]
@jozefizso Is this using Registry from PSDesiredStateConfiguration or PSDscResources?

**Comment by kwirkykat** [comment]
@jozefizso I ran this configuration and I can reproduce the error.
The problem here is not the forward slashes though. The resource is actually built to handle the forward slashes.
The problem here is the 'C:' which the resource is reading as a PSDrive.
You can see that if you take out the colon then the configuration works.
I'm looking into it.

**Comment by jozefizso** [comment]
I've tried Registry from PSDscResources and also xRegistry from xPSDesiredStateConfiguration, both were failing.

I could fix it by using this configuration:

```
  Registry FogBugzRegistry_fDebug
  {
      Key         = "HKLM:\SOFTWARE\Fog Creek Software\FogBugz\C:/Program Files (x86)/FogBugz/website"
      ValueName   = "fDebug"
      ValueData   = "0"
      Ensure      = "Present"
  }
```
