### ISSUE TITLE
Cannot Import PSDscResources

### ISSUE THREAD

**Issue by kinwolfqc** [PowerShell/PSDscResources#81]
I have the same issue as was described in #47 .  But I'm not using any insider build

<pre>
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
</pre>

As soon as I install PSDscResources, I am not able to compile any mof anymore(wheter I try to load PSDscResources or not), I always get the error 
<pre>
ImportClassResourcesFromModule : Exception calling "ImportClassResourcesFromModule" with "3" argument(s): "Resource name 'WindowsPackageCab' is already being used by another Resource or
Configuration."
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2109 char:35
+ ... rcesFound = ImportClassResourcesFromModule -Module $mod -Resources $r ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ImportClassResourcesFromModule], MethodInvocationException
    + FullyQualifiedErrorId : PSInvalidOperationException,ImportClassResourcesFromModule
</pre>

The server is a Windows 2012 R2

**Comment by mbreakey3** [comment]
Did you make sure you have all the latest windows updates? This looks like a very similar case/environment as issue #43, and installing all of the latest patches fixed his issue.

**Comment by mbreakey3** [comment]
Let me know if you're still having problems after checking this

**Comment by kinwolfqc** [comment]
Perusing the issue, I see that the patch that might solve this was never identified.  Since I am on a corporate network, many patches are not deployed if the security team thinks they are not warranted, but if the right patch is identified, I can ask for it to be installed. 

As extra information, I have also tried installing PSDscResources on a Windows 2016 server(using Install-Module PSDscResources) , and as soon as it's there, the problem appear too, even if I do not try to load PSDscResources.

**Comment by kinwolfqc** [comment]
I also tried the solution listed here: https://msdn.microsoft.com/en-us/powershell/wmf/5.0/limitation_dsc
but the result stays the same.
<pre>
Import-DscResource -ModuleName @{ModuleName='PSDscResources';RequiredVersion='2.8.0.0'}
</pre>

**Comment by mbreakey3** [comment]
I'm not sure which patch fixes this issue, but if possible, I would certainly recommend updating your machine. 
As for the 2016 machine, what is the PowerShell version installed on that machine?

**Comment by kinwolfqc** [comment]
Windows 2016 PS version. Strange, it looks older than the WMF 5.1 we downloaded for Win2012R2.  But afaik, there are no WMF 5.1 download available for Win2016.
<pre>
Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1</pre>

As for updating the 2012R2 server: corporate environment.  I have no control over that unless I open a problem in the internal ticketing.  But if I can't give them a hint of what kb to look at, I already know it will stay open forever.   I'll try to search some more.

**Comment by mbreakey3** [comment]
Do you know if there's any Windows updates for the 2016 machine? I apologize for the inconvenience this is causing. We had to make some significant changes to our system in order for this module to work since the resource names are the same as in PSDesiredStateConfiguration, so we depend on the machines have the most recent updates.

**Comment by kinwolfqc** [comment]
It might be easier for Windows 2016 since it looks like there are only cumulative updates for that OS, so the security team can't get picky about what to install.  I'll ask for the latest to be installed on my test machine and report back.

**Comment by kinwolfqc** [comment]
We installed the latest cumulative update on Windows 2016(KB4025334), rebooted, and sadly the problem is still there.  The powershell version changed to:
<pre>
Name                           Value
----                           -----
PSVersion                      5.1.14393.1532
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1532
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
</pre>

But still, as soon as I install PSDscResources, I cannot compile mof's anymore, even if I do not try to load PSDscResources inside the configuration.

**Comment by mbreakey3** [comment]
Okay, I'll look into this further and get back to you as soon as I can.

**Comment by kwirkykat** [comment]
@kinwolfqc There must be something else happening in your environment or configuration that is causing this conflict.
I have confirmed that PSDscResources works/does not work in these WMF versions:

**PsDscResources does not work**
5.1.15063.296 -- WMF 5.1 in Windows 10 Creators Update prior to 6/16/17
5.1.15063.0 -- WMF 5.1 in Windows 10 Creators Update
5.1.15055.0 -- WMF 5.1 in a past Windows Insider Update
5.1.14394.1000 -- WMF 5.1 preview version
5.0 or below
 
**PsDscResources works**
5.1.14393.953 -- version out on Windows 10/Windows Server 2016 BEFORE Creators update
5.1.14409.1005 -- downloadable WMF 5.1
5.1.15063.413 -- current version out on Windows 10 as of 6/16/17

I've tested with WMF 5.1.14409.1005 which is what you have on your Windows 2012 R2 machine and it works fine for me there.
I can't speak as confidently for the more recent versions of 5.1.14393, but I know 5.1.14393.953 worked, and as far as I know none of the problems with DSC in Windows 10 ever reached any version of Windows Server.

Did you install PSDscResources using `Install-Module`?

A *possible* (but it sounds like not probable) problem that could be occurring is that other module(s) is/are implicitly trying to import PSDesiredStateConfiguration and PSDscResources at the same time as dependencies. You can check the RequiredModules field in the module manifest (.psd1) file of any other modules you are importing in your configuration(s) to see if they are importing either of those modules as dependencies.

Could you share your configuration or maybe just the part of it where you call `Import-DscResource`?

You could also try just calling `Import-Module PSDesiredStateConfiguration` and `Import-Module PSDscResources` to see if the modules themselves will even import outside a configuration (they should if everything is working correctly).

It could also be some bizarre problem with your PSModulePath. Though I'm not really sure how.

Have you tried a different, very basic configuration like `configuration myconfig { Import-DscResource -ModuleName PSDesiredStateConfiguration } ` on the same machine?

The specific function you are having a problem with is actually in PowerShell itself, not in DSC, so you can see their most recent code for the function throwing the error in their open source code here: https://github.com/PowerShell/PowerShell/blob/ffd39b2853b68419eb0fd5e34a89b755c98b8022/src/System.Management.Automation/DscSupport/CimDSCParser.cs#L2180 (But keep in mind that code is for PowerShell Core and not the exact version of PowerShell you are using)

**Comment by kinwolfqc** [comment]
I did what you proposed, starting with a new basic configuration, and I added stuff in it until it broke.  Found the problem.  We use composite resources to keep the main script manageable.  As soon as we import that resource, we get the error message.  But I looked into the manifests of the composite resource and nowhere does it load, or ask for, PSDesiredStateConfiguration, or any other modules for that matter.  So could it be a bug in the way composite resources are called?

**Comment by kinwolfqc** [comment]
I did what you proposed, starting with a new basic configuration, and I added stuff in it until it broke.  Doing so, I was able to find the problem, but not the solution:  
We use composite resources to keep the main script manageable, and to be able to reuse the code we put in the composite resource in other configurations.  As soon as we import a composite resource, we get the error message.  But I looked into the manifests of the composite resource and nowhere does it load, or ask for, PSDesiredStateConfiguration, or any other modules for that matter. 

So I did another test, I created a completely new, and empty, composite resource and as soon as I tried to load it(with PSDscResources present) I get the dreaded 
<pre>
ImportClassResourcesFromModule : Exception calling "ImportClassResourcesFromModule" with "3" argument(s): "Resource name 'WindowsPackageCab' is already being used by another Resource or
Configuration."
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2109 char:35
+ ... rcesFound = ImportClassResourcesFromModule -Module $mod -Resources $r ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ImportClassResourcesFromModule], MethodInvocationException
    + FullyQualifiedErrorId : PSInvalidOperationException,ImportClassResourcesFromModule</pre>

 So could it be a bug in the way composite resources are called/used?

**Comment by kinwolfqc** [comment]
I use this script from Ashley McGlone to create composite resource manifests and basic files quickly
[https://gallery.technet.microsoft.com/Helper-Function-to-Create-bf248c68](url)

**Comment by kinwolfqc** [comment]
Any update on this?  Right now it seems we are offered two choices:  Either use Composite Resource and not be able to update the original PSDscResource, or be able to update PSDscResource and forego using Composite Resources(which makes our configurations pretty much unmanageable so much they get big)

**Comment by kwirkykat** [comment]
@kinwolfqc I tried out using PSDscResources along with some custom composite configurations and it all works fine for me. PSDscResources itself has several composite resources as well (all the *Set resources). So it doesn't seem to be a problem within PSDscResources.

What about in the .schema.psm1 files of the composite resources? It doesn't import any modules ore resources there either?

**Comment by kinwolfqc** [comment]
@kwirkykat Holy guacamole.  That wasn't the case for us, as we only use `Import-DscResource -Module PSDscResources -ModuleVersion 2.8.0.0` , but it did give me a hint.

Here was the line that was loading the custom resource, and gave the error:
`Import-DscResource -Module xActiveDirectory, DSQCompositeResources`
(AFAIK loading more than one module on one line  was always allowed)

Here is the simple fix making it all work:
```
Import-DscResource -Module xActiveDirectory
Import-DscResource -Module DSQCompositeResources
```
I guess DSC does something funny to the second or third module it tries to load when we use simple commas instead of repeating the whole "Import-DscResource" line?

Thanks a million for your time.  We can now use the newer PSDscResources

**Comment by dazinator** [comment]
I just hit this same bug. I am running the DSC script on a windows container: 
```
FROM microsoft/mssql-server-windows-developer:2017-latest
```

@kinwolfqc suggestion of changing to one  `Import-DscResource` per line has fixed it..
How come this is necessary though? Won't it continue to catch others out?

**Comment by aut0pil0t** [comment]
I just hit the same bug with Azure DSC as well. 🍡

**Comment by aut0pil0t** [comment]
> 
> 
> @kwirkykat Holy guacamole! What you describe wasn't the case for us, as we only use `Import-DscResource -Module PSDscResources -ModuleVersion 2.8.0.0` , but it did give me a hint.
> 
> Here was the line that was loading the custom resource, and gave the error:
> 
> ```
> Import-DscResource -Module xActiveDirectory, DSQCompositeResources
> Import-DscResource -Module PSDscResources -ModuleVersion 2.8.0.0
> ```
> 
> (AFAIK loading more than one module on one line was always allowed as it never caused us any problem until we tried also loading PsDscResources)
> 
> Here is the simple fix making it all work:
> 
> ```
> Import-DscResource -Module xActiveDirectory
> Import-DscResource -Module DSQCompositeResources
> Import-DscResource -Module PSDscResources -ModuleVersion 2.8.0.0
> ```
> 
> I guess DSC does something funny to the second or third module it tries to load when we use simple commas instead of repeating the whole "Import-DscResource" line?
> 
> Thanks a million for your time. We can now use the newer PSDscResources

I just hit the same bug with Azure DSC as well. 🍡
