### ISSUE TITLE
MSFT_Archeive Resource failed to executed Test-TargetResource functionality

### ISSUE THREAD

**Issue by Rmpanga** [PowerShell/PSDscResources#85]
Hi, 

I am attempting to use the DSC Archive Resource but I am running into this error message. 

` Failed to executed Test-TargetResource functionality with error message: 
An error occurred while opening the file C:\Program Files (x86)\longpath\VMUtil.pm
`

I was able to unzip the file manually and use the File Resourse to move the files with out issue. I would prefer to use the Archive Resource instead on manually unzipping the zip files.

**Comment by ld0614** [comment]
Hi @Rmpanga if the issue is the extraction to the long path name(above 260 Characters) as it seems to suggest in your initial report have you considered working around the issue by using the archive to extract to somewhere short such as C:\Temp and then use a File Resource to move the files where they are needed as a separate action?

**Comment by Rmpanga** [comment]
Yes, I have this workaround. I have a non dsc script that unzips the file and use the file resource to copy over the files. Is the archive resource not intended to unzip and place the files in a specific location?

**Comment by ld0614** [comment]
While the archive file is intended for this purpose it is limited but the fact that it is built using PowerShell and PowerShell is limited by the fact that it is built on .Net.  Specifically .Net utilizes the System.IO library which until .Net 4.6.2 was limited to 260 characters long ([REF](https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/4954037-fix-260-character-file-name-length-limitation)).  This limitation has now been removed but only for operating systems that support this ([Windows 10 Creators Update and above](https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/)) I'm not aware of this functionality being available on Windows Server yet.

**Comment by Rmpanga** [comment]
Thanks for the information.
