### ISSUE TITLE
Group: Creates error on forcing members for builtin Administrators group

### ISSUE THREAD

**Issue by tmeckel** [PowerShell/PSDscResources#87]
# Symptom

MSFT_GroupResource will create the following error, if memebers for the builtin group Administrators will be forced via the "Members" attribute

`Error Message is Exception calling "Save" with "0" argument(s): "Cannot perform this operation on built-in accounts.`

# Steps to reproduce

1. Create a DSC Configuration
2. Use the Group resssource and force the memebrs of teh Administrators group to the following contents: 

```
Group GroupExample
{
    Ensure = "Present"
    GroupName = "Administrators"
    Members = @( ".\Administrator", "<Domain>\<SamAccountName>")
}
```

3. Apply the configuration to the node

# Analysis

By tracking down the error the deletion of all members of a group via `$group.Members.Clear()` could be assigned as the culprit of the error. The latter issued command `$group.Save()` will first submit the `clear()` command to the group which will be prevented by the OS because the `Administrators` group must contain at least contain the local administrator account from the node (localhost). The `Administrators` group cannot be empty.

# Fix

Instead of simply deleteing all members from the group and reassigning the ones from the input parameter `Members` the implementation must **merge** the group members between the current members of the group and the input parameter. The following changes has been applied to MSFT_GroupResource.psm1 to resolve the error:

New (internal) function:
```
function MergeGroupMembers
{
    [OutputType([bool])]
    param
    (
        [System.DirectoryServices.AccountManagement.GroupPrincipal] $Group,
        [System.DirectoryServices.AccountManagement.Principal[]] $Principals
    )
    Set-StrictMode -Version Latest
    [bool] $updated = $false
    if ($Principals -ne $null)
    {        
        foreach($principal in $Principals)
        {
            if ($group.Members.Contains($principal))
            {
                continue
            }	    
            Write-Verbose ("Adding principal [$principal] to group [$group]")	    
            $group.Members.Add($principal)
            $updated = $true
        }
        foreach($principal in @($group.Members)) 
        {
            if ($Principals.Contains($principal))
            {
                continue
            }	    
            if ($group.Sid -eq "S-1-5-32-544" -and $principal.Sid -like "S-1-5-21-*-500") {
                Write-Verbose ("Skipping local admin account [$principal] for administrators group [$group]")
                continue
            }
            Write-Verbose ("Removing principal [$principal] from group [$group]")
            $group.Members.Remove($principal)
            $updated = $true
        }
    }
    return $updated
}
```

Changed the code startign at line 446 as following

 ```
if ((MergeGroupMembers -Group $group -Principals $expectedPrincipals) -eq $true)
{
       $saveChanges = $true
}
```

# Remarks

Find attached  a zip file with additional information.
[MSFT_GroupResource_Error.zip](https://github.com/PowerShell/PSDscResources/files/1380503/MSFT_GroupResource_Error.zip)

**Comment by mbreakey3** [comment]
I appreciate the detailed description - feel free to open a Pull Request with these changes.

**Comment by tmeckel** [comment]
I verfied that the code, that I've changed, never has been imported into GitHub. The code I patched is from the PSDesiredStateConfiguration Module Version 1.1 which is shipped with WMF 5.1. 
So as far that I can see, no need to change anything here, because the offending CLEAR statement isn't used here in the GitHub code.
 
The only thing that might be improved is the test, that the local administrator account isn't removed from the local Adminitrators group. Because that would create a exception if the changes would be committed.

Let me know if I should provide a pull request for that, or if you let this change be implemented by other means.

**Comment by johlju** [comment]
The potentially offending `$Group.Members.Clear()` is called here

https://github.com/PowerShell/PSDscResources/blob/9f5e9e48eda63b5ff0ab5ad179173b754863c49e/DscResources/MSFT_GroupResource/MSFT_GroupResource.psm1#L2439

So what @tmeckel suggest might need to be done, adding a regression test that clears Administrators group and make sure it can be handled.

@tmeckel If you are still up for this, please send in a PR.

**Comment by tmeckel** [comment]
Sorry @johlju! I didn't watch that issue closely. Shall I still provide a PR for that issue?

**Comment by tmeckel** [comment]
@johlju Quick question: the (local) Administrators groups uses I18N names, depending on the installed (primary) language of the Windows Computer. So in English (LCID: 1033) the group is named "Administrators". On a system installed with German (LCDI: 1031) as primary language the group is named "Administratoren".  

So how to write the Pester regression test for the issue here?

As far as  I can see the Pester Unit tests for MSFT_GroupResource uses  the `$script:testGroupName` parameter. This can't be used here either. So what's, from you point of view, the best thing to do to implement the test?

**Comment by johlju** [comment]
The local group 'Administrators' has the SID S-1-5-32-544. Could we get the group by SID using `(Get-LocalGroup -SID 'S-1-5-32-544').Name` and use that in the tests?

**Comment by tmeckel** [comment]
Okay ... I was dumb! :-D Great idea .. I could've come up with that myself.

**Comment by johlju** [comment]
Not dumb at all! Working together gave a solution faster. I wouldn't even have thought of making the test localized like you did! Great work 👍 🙂

**Comment by tmeckel** [comment]
@johlju  I finalized the changes inside the code. I discovered some more places where it's possible to remove the local admin account from the local Admnistrators group, which might lead to an exception if the changes are committed.  For each change I'll add a Pester test. When I'm done I'll create a merge request. Or would you like to do quick review of the changes inside my repo at first?

**Comment by johlju** [comment]
@tmeckel Please send in a PR once you feel you are finished. It is easier for me to review a PR. 🙂

**Comment by tmeckel** [comment]
@johlju  I just added a pull request containing the fixes for this issue. Sorry for the delay.

**Comment by johlju** [comment]
@tmeckel If the change is needed in xPSDesiredStateConfiguration then pleaseopen a PR there as well. The tow repositories have there own lifecycle and are not ported either way.

**Comment by tmeckel** [comment]
@johlju it's definitly required. The offending Clear() statement ist present here as well

https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/5a205a582b433f11e3109179aeb041f9999c207c/DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1#L2439

Do I have to open an issue at xPSDesiredStateConfiguration for this. Or can I simply provide a PR?

**Comment by johlju** [comment]
@tmeckel It is appreciated if you create an issue, then the community to discuss the issue if needed. The new issue could reference this issue for more details. Then refer the new PR to the newly created issue.

**Comment by tmeckel** [comment]
> @tmeckel It is appreciated if you create an issue, then the community to discuss the issue if needed. The new issue could reference this issue for more details. Then refer the new PR to the newly created issue.

@johlju I created an issue https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/467 at xPSDesiredStateConfiguration
