### ISSUE TITLE
Renaming an existing user with DSC

### ISSUE THREAD

**Issue by Warryz** [PowerShell/PSDscResources#92]
Hello,

I'm interested in renaming an existing user with DSC. As I saw so far, the only thing you can do with the module PSDscResources is creating or deleting users. 

I'm thinking of creating a resource for this purpose. Is this the right repo for this or is there any other?

**Comment by mbreakey3** [comment]
So, DSC is used for monitoring the state of a machine and changing the configuration of the machine if necessary. Since there isn't really a way to monitor renaming a user this doesn't sound like a DSC scenario, but correct me if you have further implementation ideas on this in which this would fit for DSC.

**Comment by Warryz** [comment]
For security purpose I used to lock and rename the local default Administrator and guest account on windows servers. Of course you can do it also with a script that is executed by DSC but that's not **the** kind of DSC flair. Either you do it all by DSC or you don't. 👍

I thought of doing it like renaming an interface, like on the xNetworking module [here](https://github.com/PowerShell/xNetworking/tree/dev/Modules/xNetworking/DSCResources/MSFT_xNetAdapterName).

**Comment by Warryz** [comment]
I don't think it's necessary to implement this into this module, I did it with the script resource. Thank you. 😄

**Comment by gaelicWizard** [comment]
Hello, I would like to request this exact same thing. Should I make a whole new issue and add my use case there or do I re-open this issue with my use case?

**Comment by gaelcolas** [comment]
Hey @gaelicWizard, this as Mariah answered in 2017, this does not sound like a valid "Desired State" scenario. It sounds more like a "Transform"... It would probably best that you [join the community on Slack/discord](https://dsccommunity.org/community/contact/) to discuss your scenario and benefit from the collective experience.

This specific resource module (`PsDscResources`) would not be the right place for such change anyway, as the only goal is to replace like for like the built-in DSC resources with security and bug fixes (no new feature as this issue suggests).
A better place would be [`xPsDesiredStateConfiguration`](https://github.com/dsccommunity/xPSDesiredStateConfiguration) which is more advanved than this resource module.

**Comment by gaelicWizard** [comment]
Thanks! I didn't think about PsDscResources vs xPsDesiredStateConfiguration. I definitely mean to go there 👍
