### ISSUE TITLE
Warning when using File resource from PSDesiredStateConfiguration

### ISSUE THREAD

**Issue by ewhitesides** [PowerShell/PSDscResources#95]
Would it be possible to include the File resource in PSDscResources, even if nothing has changed from PSDesiredStateConfiguration? 

Otherwise, you get a bunch of conflict warnings when you try to Import-Module PSDscResources and Import-Module PSDesiredStateConfiguration into the same config.

**Comment by mbreakey3** [comment]
Unfortunately not. This resource is actually written in native code so it's a bit more complicated to port it over to this module. There's another known bug with importing the File resource (#90) that we also haven't been able to release a fix a for (that's what's causing the warnings/error messages). There are some workarounds that are mentioned in the above issue, but that's pretty much the only options right now.

**Comment by johlju** [comment]
Closing this as answered.
